import Foundation

/// Post-STT heard-to-written rules harvested from public Whisper / Wispr-class
/// dictation repos, plus the daily AI-tool mishears Nate actually hits.
///
/// These are exact replacements. They are not Whisper-prompt stuffing.
/// Single-word English homographs stay out (`cloud`, `cursor`, `sonnet`,
/// `jason`, `react`). Slack-style rewrites of ordinary English stay out.
///
/// Sources (read-only smelt, 2026-08-15):
/// - verygoodplugins/superwhisper-trainer `data/known_terms.yaml` + `presets/developer.yaml`
/// - semikolon/karabiner-mods `docs/superwhisper_integration.md`
/// - TypeWhisper/typewhisper-win `TermPack.AllPacks` (canonical terms, not from-to)
/// - marcus-cali/claude-voice-channels README (`clock code`, `enthropy`)
/// - hourliert/VoiceInk-Qwen3.5-2B-FT README (`cloud code` -> Claude Code)
/// - Beingpax/VoiceInk, cjpais/Handy, OpenWhispr/openwhispr (dictionary features, no default bank)
public enum HeardWrittenPack {
    public static let terms: [String] = [
        "Anthropic",
        "ChatGPT",
        "Claude Code",
        "Claude Haiku",
        "Claude Opus",
        "Claude Sonnet",
        "Cloudflare",
        "Copilot",
        "Cursor",
        "FastAPI",
        "GitHub Actions",
        "GitHub Copilot",
        "GitLab",
        "GraphQL",
        "Hugging Face",
        "JavaScript",
        "Kubernetes",
        "LangChain",
        "LlamaIndex",
        "MongoDB",
        "MySQL",
        "Next.js",
        "Node.js",
        "Ollama",
        "OpenAI",
        "Perplexity",
        "PostgreSQL",
        "Qwen",
        "SuperWhisper",
        "TypeScript",
        "TypeWhisper",
        "VoiceInk",
        "VS Code",
        "jQuery",
    ]

    public static let replacements: [VocabularyPostProcessor.Replacement] = [
        // MARK: Claude / ChatGPT  -  Nate-facing (Karabiner SuperWhisper + VoiceInk-Qwen + claude-voice)
        .init(from: "local boys", to: "Local Voice"),
        .init(from: "vocal voice", to: "Local Voice"),
        .init(from: "clod", to: "Claude"),
        .init(from: "clod code", to: "Claude Code"),
        .init(from: "clawed code", to: "Claude Code"),
        .init(from: "clock code", to: "Claude Code"),
        .init(from: "cloud code", to: "Claude Code"),
        .init(from: "cloudcode", to: "Claude Code"),
        .init(from: "claude code", to: "Claude Code"),
        .init(from: "clod.md", to: "CLAUDE.md"),
        .init(from: "clod md", to: "CLAUDE.md"),
        .init(from: "claude md", to: "CLAUDE.md"),
        .init(from: "claude.md", to: "CLAUDE.md"),
        .init(from: "chat gpt", to: "ChatGPT"),
        .init(from: "chatgpt", to: "ChatGPT"),
        .init(from: "chat-gpt", to: "ChatGPT"),
        .init(from: "chat gee pee tee", to: "ChatGPT"),
        .init(from: "chat gee pee t", to: "ChatGPT"),
        .init(from: "chat jee pee tee", to: "ChatGPT"),
        .init(from: "chat gbt", to: "ChatGPT"),
        .init(from: "chat g p t", to: "ChatGPT"),
        .init(from: "chat gipity", to: "ChatGPT"),
        .init(from: "chat gippity", to: "ChatGPT"),
        .init(from: "chat jippity", to: "ChatGPT"),
        .init(from: "chatubt", to: "ChatGPT"),
        .init(from: "chatubti", to: "ChatGPT"),
        .init(from: "open ai", to: "OpenAI"),
        .init(from: "open a i", to: "OpenAI"),
        .init(from: "openai", to: "OpenAI"),
        .init(from: "enthropy", to: "Anthropic"),
        .init(from: "enthropic", to: "Anthropic"),
        .init(from: "enthalpy", to: "Anthropic"),
        .init(from: "an thropic", to: "Anthropic"),
        .init(from: "an throw pick", to: "Anthropic"),
        .init(from: "gee pee tee", to: "GPT"),
        .init(from: "gpt 4", to: "GPT-4"),
        .init(from: "gpt four", to: "GPT-4"),
        .init(from: "gpt-4", to: "GPT-4"),
        .init(from: "gpt 5", to: "GPT-5"),
        .init(from: "gpt five", to: "GPT-5"),
        .init(from: "gpt-5", to: "GPT-5"),
        .init(from: "claude sonnet", to: "Claude Sonnet"),
        .init(from: "claude opus", to: "Claude Opus"),
        .init(from: "claude haiku", to: "Claude Haiku"),
        .init(from: "kodaks", to: "Codex"),
        .init(from: "kodak's", to: "Codex"),
        .init(from: "codecs", to: "Codex"),
        .init(from: "groc", to: "Grok"),
        .init(from: "kermaz", to: "Hermes"),
        .init(from: "kwen", to: "Qwen"),
        .init(from: "olama", to: "Ollama"),
        .init(from: "andros", to: "Andras"),
        .init(from: "god mode", to: "GODMODE"),
        .init(from: "effort rounder", to: "effort-router"),
        .init(from: "notebook lm", to: "NotebookLM"),
        .init(from: "smelt rebo", to: "smelt-repo"),
        .init(from: "oz dash loop", to: "oz-loop"),
        .init(from: "oz dash result", to: "oz-result"),
        .init(from: "oz dash start", to: "oz-start"),
        .init(from: "oz dash gauntlet", to: "oz-gauntlet"),
        .init(from: "open whisper", to: "OpenWhispr"),
        .init(from: "type whisper", to: "TypeWhisper"),
        .init(from: "get element byld", to: "getElementById"),
        .init(from: "get element build", to: "getElementById"),
        .init(from: "laying chain", to: "LangChain"),
        .init(from: "peak digest", to: "peek digest"),
        .init(from: "cipher lab os", to: "CipherOS"),
        .init(from: "open parenthesis", to: "("),
        .init(from: "close parenthesis", to: ")"),
        .init(from: "end parenthesis", to: ")"),
        .init(from: "left parenthesis", to: "("),
        .init(from: "right parenthesis", to: ")"),
        .init(from: "github copilot", to: "GitHub Copilot"),
        .init(from: "git hub copilot", to: "GitHub Copilot"),
        .init(from: "get hub copilot", to: "GitHub Copilot"),
        .init(from: "cursor ai", to: "Cursor"),
        .init(from: "cursor ide", to: "Cursor"),
        .init(from: "super whisper", to: "SuperWhisper"),
        .init(from: "voice ink", to: "VoiceInk"),
        .init(from: "ultra think", to: "Ultrathink"),

        // MARK: SuperWhisper trainer developer.yaml  -  distinctive tech only
        .init(from: "console log", to: "console.log"),
        .init(from: "console error", to: "console.error"),
        .init(from: "console warn", to: "console.warn"),
        .init(from: "get element by id", to: "getElementById"),
        .init(from: "query selector all", to: "querySelectorAll"),
        .init(from: "query selector", to: "querySelector"),
        .init(from: "add event listener", to: "addEventListener"),
        .init(from: "get lab", to: "GitLab"),
        .init(from: "git lab", to: "GitLab"),
        .init(from: "my sequel", to: "MySQL"),
        .init(from: "my sql", to: "MySQL"),
        .init(from: "postgres", to: "PostgreSQL"),
        .init(from: "post gres", to: "PostgreSQL"),
        .init(from: "post gre sql", to: "PostgreSQL"),
        .init(from: "postgressql", to: "PostgreSQL"),
        .init(from: "mongo db", to: "MongoDB"),
        .init(from: "node js", to: "Node.js"),
        .init(from: "j query", to: "jQuery"),
        .init(from: "jay query", to: "jQuery"),
        .init(from: "dot env", to: ".env"),
        .init(from: "dot git ignore", to: ".gitignore"),
        .init(from: "package jason", to: "package.json"),
        .init(from: "docker file", to: "Dockerfile"),

        // MARK: known_terms.yaml spoken / dotted forms (SuperWhisper trainer)
        .init(from: "next js", to: "Next.js"),
        .init(from: "next.js", to: "Next.js"),
        .init(from: "nuxt js", to: "Nuxt"),
        .init(from: "type script", to: "TypeScript"),
        .init(from: "graph ql", to: "GraphQL"),
        .init(from: "hugging face", to: "Hugging Face"),
        .init(from: "lang chain", to: "LangChain"),
        .init(from: "llama index", to: "LlamaIndex"),
        .init(from: "web assembly", to: "WebAssembly"),
        .init(from: "tail wind", to: "Tailwind"),
        .init(from: "fast api", to: "FastAPI"),
        .init(from: "spring boot", to: "Spring Boot"),
        .init(from: "elastic search", to: "Elasticsearch"),
        .init(from: "kubernettes", to: "Kubernetes"),
        .init(from: "kube rnetes", to: "Kubernetes"),
        .init(from: "cloud flare", to: "Cloudflare"),
        .init(from: "digital ocean", to: "DigitalOcean"),
        .init(from: "big query", to: "BigQuery"),
        .init(from: "git hub actions", to: "GitHub Actions"),
        .init(from: "get hub actions", to: "GitHub Actions"),
        .init(from: "vs code", to: "VS Code"),
        .init(from: "visual studio code", to: "VS Code"),
        .init(from: "wp fusion", to: "WP Fusion"),
        .init(from: "active campaign", to: "ActiveCampaign"),
        .init(from: "github actions", to: "GitHub Actions"),
        .init(from: "jet pack compose", to: "Jetpack Compose"),
        .init(from: "entity framework", to: "Entity Framework"),
        .init(from: "zero trust", to: "Zero Trust"),
        .init(from: "sql injection", to: "SQL Injection"),
        .init(from: "material design", to: "Material Design"),
        .init(from: "huggingface", to: "Hugging Face"),
        .init(from: "langchain", to: "LangChain"),
        .init(from: "llamaindex", to: "LlamaIndex"),
        .init(from: "ollama", to: "Ollama"),
        .init(from: "mid journey", to: "Midjourney"),
    ]
}
