import Foundation

/// Nate's standing CipherOS / 2OPMD / Cipher Lab vocabulary.
///
/// Seeded from CLAUDE.md lane terms plus Local Voice history takes.
/// Proper nouns and acronyms only, never common English.
public enum OperatorVocabulary {
    public static let terms: [String] = [
        "2nd Opinion MD",
        "2OPMD",
        "Andras",
        "Automic Vault",
        "CipherOG",
        "CMUX",
        "Cipher",
        "Cipher Holdings",
        "Cipher Lab",
        "CipherOS",
        "Claude",
        "Codex",
        "Dylan",
        "ENTEXS",
        "ELI5",
        "EoH",
        "EoHD",
        "Excalidraw",
        "Exploit Poker",
        "Fable",
        "FirstMate",
        "FORWARD",
        "Gauntlet",
        "Gemini",
        "GitHub",
        "Grok",
        "Herdr",
        "Hermes",
        "Higgsfield",
        "Kimi",
        "Kun",
        "Kun Chen",
        "Laird",
        "Laird's",
        "Local Voice",
        "MKE",
        "MKG",
        "Nate",
        "Nemesis",
        "NoteCamp",
        "OGrE",
        "Oz",
        "oz-gauntlet",
        "oz-loop",
        "oz-result",
        "oz-skilltree",
        "oz-start",
        "OzSkillTree",
        "Parakeet",
        "PokerGod",
        "PTV",
        "RISE",
        "Titan Trading",
        "Wayfinder",
        "Wispr Flow",
        "WizardOZ",
    ]

    public static let replacements: [VocabularyPostProcessor.Replacement] = [
        .init(from: "cypher", to: "Cipher"),
        .init(from: "cypher os", to: "CipherOS"),
        .init(from: "cipher os", to: "CipherOS"),
        .init(from: "cipher owes", to: "CipherOS"),
        .init(from: "cipher og", to: "CipherOG"),
        .init(from: "cypher og", to: "CipherOG"),
        .init(from: "ogre", to: "OGrE"),
        .init(from: "oh gree", to: "OGrE"),
        .init(from: "two op md", to: "2OPMD"),
        .init(from: "second opinion md", to: "2nd Opinion MD"),
        .init(from: "first mate", to: "FirstMate"),
        .init(from: "firstmate", to: "FirstMate"),
        .init(from: "get hub", to: "GitHub"),
        .init(from: "get hubs", to: "GitHub"),
        .init(from: "get-hub", to: "GitHub"),
        .init(from: "get-hubs", to: "GitHub"),
        .init(from: "git hub", to: "GitHub"),
        .init(from: "note camp", to: "NoteCamp"),
        .init(from: "note quest", to: "NoteCamp"),
        .init(from: "poker god", to: "PokerGod"),
        .init(from: "exploit poker", to: "Exploit Poker"),
        .init(from: "wizard oz", to: "WizardOZ"),
        .init(from: "oz skill tree", to: "oz-skilltree"),
        .init(from: "oz skilltree", to: "oz-skilltree"),
        .init(from: "ozstart", to: "oz-start"),
        .init(from: "oz start", to: "oz-start"),
        .init(from: "oz loop", to: "oz-loop"),
        .init(from: "oz dash loop", to: "oz-loop"),
        .init(from: "ozresult", to: "oz-result"),
        .init(from: "oz result", to: "oz-result"),
        .init(from: "oz gauntlet", to: "oz-gauntlet"),
        .init(from: "dauntlet", to: "gauntlet"),
        .init(from: "wispr flow", to: "Wispr Flow"),
        .init(from: "whisper flow", to: "Wispr Flow"),
        .init(from: "local voice", to: "Local Voice"),
        .init(from: "automic vault", to: "Automic Vault"),
        .init(from: "atomic vault", to: "Automic Vault"),
        .init(from: "titan trading", to: "Titan Trading"),
        .init(from: "en texs", to: "ENTEXS"),
        .init(from: "entexs", to: "ENTEXS"),
        .init(from: "koon chan", to: "Kun Chen"),
        .init(from: "kuhn chan", to: "Kun Chen"),
        .init(from: "kunchan", to: "Kun Chen"),
        .init(from: "kun chan", to: "Kun Chen"),
        .init(from: "kunch", to: "Kun Chen"),
        .init(from: "cmux", to: "CMUX"),
        .init(from: "eli 5", to: "ELI5"),
        .init(from: "e l i 5", to: "ELI5"),
        .init(from: "eli five", to: "ELI5"),
        .init(from: "e l i five", to: "ELI5"),
        .init(from: "explain like i'm five", to: "ELI5"),
        .init(from: "explain like i am five", to: "ELI5"),
        .init(from: "explain like im five", to: "ELI5"),
        .init(from: "eoh", to: "EoH"),
        .init(from: "eohd", to: "EoHD"),
        .init(from: "ptv", to: "PTV"),
        .init(from: "herder", to: "Herdr"),
        .init(from: "higgs field", to: "Higgsfield"),
        .init(from: "way finder", to: "Wayfinder"),
        .init(from: "scallodraw", to: "Excalidraw"),
        .init(from: "excali draw", to: "Excalidraw"),
        .init(from: "orgystrator", to: "orchestrator"),
    ]
}
