import Foundation

/// Nate's standing CipherOS / 2OPMD / Cipher Lab vocabulary.
///
/// Seeded from CLAUDE.md lane terms plus 342 Local Voice history takes and
/// recent dictation chats. These are proper nouns and acronyms only, never
/// common English, so they cannot recreate the "in the" -> "Kun Chen" failure.
public enum OperatorVocabulary {
    public static let terms: [String] = [
        "2nd Opinion MD",
        "2OPMD",
        "Andras",
        "Automic Vault",
        "CMUX",
        "Cipher",
        "Cipher Holdings",
        "Cipher Lab",
        "CipherOS",
        "Claude",
        "Codex",
        "Dylan",
        "ENTEXS",
        "EoH",
        "EoHD",
        "Exploit Poker",
        "Fable",
        "FirstMate",
        "FORWARD",
        "Gemini",
        "GitHub",
        "Grok",
        "Hermes",
        "Higgsfield",
        "Kimi",
        "Kun",
        "Kun Chen",
        "Laird",
        "Laird's",
        "Local Voice",
        "MKE",
        "MKG",
        "Nate",
        "NoteCamp",
        "OGrE",
        "Oz",
        "OzSkillTree",
        "Parakeet",
        "PokerGod",
        "PTV",
        "RISE",
        "Titan Trading",
        "Wispr Flow",
        "WizardOZ",
    ]

    public static let replacements: [VocabularyPostProcessor.Replacement] = [
        .init(from: "cypher", to: "Cipher"),
        .init(from: "cypher os", to: "CipherOS"),
        .init(from: "cipher os", to: "CipherOS"),
        .init(from: "cipher owes", to: "CipherOS"),
        .init(from: "ogre", to: "OGrE"),
        .init(from: "oh gree", to: "OGrE"),
        .init(from: "two op md", to: "2OPMD"),
        .init(from: "second opinion md", to: "2nd Opinion MD"),
        .init(from: "first mate", to: "FirstMate"),
        .init(from: "firstmate", to: "FirstMate"),
        .init(from: "get hub", to: "GitHub"),
        .init(from: "get hubs", to: "GitHub"),
        .init(from: "git hub", to: "GitHub"),
        .init(from: "note camp", to: "NoteCamp"),
        .init(from: "note quest", to: "NoteCamp"),
        .init(from: "poker god", to: "PokerGod"),
        .init(from: "exploit poker", to: "Exploit Poker"),
        .init(from: "wizard oz", to: "WizardOZ"),
        .init(from: "oz skill tree", to: "OzSkillTree"),
        .init(from: "wispr flow", to: "Wispr Flow"),
        .init(from: "whisper flow", to: "Wispr Flow"),
        .init(from: "local voice", to: "Local Voice"),
        .init(from: "automic vault", to: "Automic Vault"),
        .init(from: "titan trading", to: "Titan Trading"),
        .init(from: "en texs", to: "ENTEXS"),
        .init(from: "entexs", to: "ENTEXS"),
        .init(from: "koon chan", to: "Kun Chen"),
        .init(from: "kuhn chan", to: "Kun Chen"),
        .init(from: "kunch", to: "Kun Chen"),
        .init(from: "cmux", to: "CMUX"),
        .init(from: "eoh", to: "EoH"),
        .init(from: "eohd", to: "EoHD"),
        .init(from: "ptv", to: "PTV"),
    ]
}
